#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
%define keepstatic 1
Name     : rip
Version  : 0.13.1
Release  : 7
URL      : file:///aot/build/clearlinux/packages/rip/rip-0.13.1.tar.gz
Source0  : file:///aot/build/clearlinux/packages/rip/rip-0.13.1.tar.gz
Summary  : No detailed summary available
Group    : Development/Tools
License  : GPL-2.0
Requires: rip-bin = %{version}-%{release}
BuildRequires : autoconf-archive-dev
BuildRequires : ca-certs
BuildRequires : ca-certs-static
BuildRequires : grep
BuildRequires : intltool
BuildRequires : intltool-dev
BuildRequires : openssl
BuildRequires : openssl-dev
BuildRequires : rustc
BuildRequires : rustc-bin
BuildRequires : rustc-data
BuildRequires : rustc-dev
BuildRequires : rustc-staticdev
BuildRequires : termcolor
BuildRequires : time
# Suppress stripping binaries
%define __strip /bin/true
%define debug_package %{nil}

%description
* rip (Rm ImProved)
[[https://crates.io/crates/rm-improved][https://img.shields.io/crates/v/rm-improved.svg]]
[[https://travis-ci.org/nivekuil/rip][https://travis-ci.org/nivekuil/rip.svg?branch=master]]

%package bin
Summary: bin components for the rip package.
Group: Binaries

%description bin
bin components for the rip package.


%prep
%setup -q -n rip
cd %{_builddir}/rip

%build
unset http_proxy
unset https_proxy
unset no_proxy
export SSL_CERT_FILE=/var/cache/ca-certs/anchors/ca-certificates.crt
RUSTFLAGS="-C target-cpu=native"
export SSL_CERT_FILE=/var/cache/ca-certs/anchors/ca-certificates.crt
cargo update --verbose

%install
RUSTFLAGS="-C target-cpu=native"
export SSL_CERT_FILE=/var/cache/ca-certs/anchors/ca-certificates.crt
RUSTFLAGS="-C target-cpu=native" cargo install --verbose --no-track --path . --root %{buildroot}/usr/
## install_append content
# shell completion for bash
# install -dm 0755 %{buildroot}/usr/share/bash-completion/completions
# install -m0644 ./target/release/build/ripgrep-*/out/rg.bash %{buildroot}/usr/share/bash-completion/completions/rg
# rm -rf ./target/release/build/ripgrep-*/out/rg.bash
# man docs
# install -dm 0755 %{buildroot}/usr/share/man/man1
# install -m0644 ./target/release/build/ripgrep-*/out/rg.1 %{buildroot}/usr/share/man/man1/rg.1
## install_append end

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/rip
